inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**
    - config.ru
    - db/migrate/**
    - db/schema.rb

Rails:
  Enabled: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 165
  Exclude:
    - 'spec/lib/was/importer/data_importer_from_text_spec.rb'
    - 'spec/lib/was/registrar/register_crawl_object_from_file_spec.rb'
    - 'spec/lib/was/registrar/register_crawl_object_spec.rb'
    - 'spec/lib/was/registrar/source_xml_writer_spec.rb'

# Far more languages and notations use /regex/ than %r
# rspec `.to match(/regex/)` is also conventional
Style/RegexpLiteral:
  Enabled: false
