default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  database: was_registrar
  username: root
  encoding: utf8

test:
  adapter: mysql2
  database: was_registrar
  username: root
  encoding: utf8