# these are set on our VMs with shared_configs branches.  to use locally,
# create config/settings/development.local.yml and populate

# seed_apo: APO used when creating DOR seed objects.  format 'druid:xx123yy4567'
seed_apo: 'oo000oo0000'

# seed_staging_path: where the seeds_controller outputs XML representing the seed object;
#  this XML is read later by was_robot_suite wasSeedPreassemblyWF step
seed_staging_path: './'

# Dor Services Client configuration
DOR_SERVICES:
  URL: 'http://localhost:3003'

# argo_view_url: prepended to druid;  used for links to registered objects in views
#  format: yes, trailing slash, e.g. 'https://argo-stage.stanford.edu/catalog/'
argo_view_url: ''

workflow:
  url: 'http://workflow.example.com/'
